---
name: Syntax Tests

on:
  push:
    paths:
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'
  pull_request:
    paths:
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'
  workflow_dispatch:

jobs:
  syntax_tests:
    name: Syntax Tests (ST ${{ matrix.build }})
    strategy:
      matrix:
        include:
          - build: 'latest'
          # Latest known ST3 build with a test binary.
          - build: 3210

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: SublimeText/syntax-test-action@v2
        with:
          build: ${{ matrix.build }}
